name: InventoryExample
version: ${project.version}
main: xyz.dysaido.inventory.sample.InventoryExample
load: STARTUP
author: Dysaido
description: This is an inventory api for bukkit plugins

commands:
  testinv: